# Generated by Django 3.2.4 on 2021-06-10 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('openmrs', models.CharField(blank=True, max_length=100, null=True)),
                ('categoryOptionCombo', models.CharField(blank=True, max_length=200, null=True)),
                ('attributeOptionCombo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpenMRSURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('instance_name', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('openmrs_name', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district')),
            ],
            options={
                'verbose_name': 'Health Facility',
                'verbose_name_plural': 'Health Facilities',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province'),
        ),
        migrations.CreateModel(
            name='DataSetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=200)),
                ('completeDate', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False)),
                ('dataSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
                ('orgUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.healthfacility')),
            ],
        ),
        migrations.CreateModel(
            name='DataElementValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('dataElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataelement')),
                ('dataSetValue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.datasetvalue')),
            ],
        ),
        migrations.AddField(
            model_name='dataelement',
            name='dataSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset'),
        ),
    ]
